language: csharp
branches:
  except:
  - /^[0-9]/
services:
  - docker
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
matrix:
  include:
    - os: linux
      sudo: required
      dotnet: 2.0.0
    - os: osx 
      osx_image: xcode9 # OSX 10.12
      dotnet: 2.0.0
script:
  - ./build.sh
notifications:
  on_success: always
  on_failure: always
  on_start: always
