assembly-versioning-scheme: MajorMinorPatch
mode: ContinuousDeployment

# It would be better to use smarter regexes instead of duplicating everything for local and remote cases.
# However, GitVersion has some built-in patterns which cannot be removed and these would cause clashes.
branches:
  
  # These branch patterns cover all local cases
  master:
    regex: master
    tag: master
    increment: Minor
    prevent-increment-of-merged-branch-version: true
  feature:
    regex: feature[/-]
    tag: a{BranchName}
    increment: Minor
    prevent-increment-of-merged-branch-version: false
  patch:
    regex: patch[/-]
    tag: useBranchName
    increment: Patch
    prevent-increment-of-merged-branch-version: false
  release:
    regex: release[/-]
    tag: rc
    increment: None
    prevent-increment-of-merged-branch-version: false
  
  # These branch patterns cover all remote cases
  origin/master:
    regex: origin/master
    tag: master
    increment: Minor
    prevent-increment-of-merged-branch-version: true
  origin/feature:
    regex: origin/feature[/-]
    tag: a{BranchName}
    increment: Minor
    prevent-increment-of-merged-branch-version: false
  origin/patch:
    regex: origin/patch[/-]
    tag: useBranchName
    increment: Patch
    prevent-increment-of-merged-branch-version: false
  origin/release:
    regex: origin/release[/-]
    tag: rc
    increment: None
    prevent-increment-of-merged-branch-version: false